ktor:
    development: ${DEVELOPMENT:false}
    application:
        modules:
            - com.oliver.ApplicationKt.module
    deployment:
        reload: ${RELOAD:false}
        watch:
          - build/classes/kotlin/main
          - build/resources/main
        port: ${PORT:8080}
        host: 0.0.0.0
    elevenlabs:
        key: ${ELEVENLABS_KEY}