ktor:
    development: true
    application:
        modules:
            - com.oliver.ApplicationKt.module
    deployment:
        reload: true
        watch:
          - build/classes/kotlin/main
          - build/resources/main
        port: 8080
    elevenlabs:
        key: ${ELEVENLABS_KEY}